<?php

use \Magento\Framework\Data\Helper\PostHelper;
use \Xigen\OrderHistory\Helper\Reorder;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Xigen\OrderHistory\Block\Sales\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?= $block->escapeHtml($_order->getIncrementId()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                            <?= /* @noEscape */ $block->formatPrice(
                                $_order->getGrandTotal(),
                                $_order->getOrderCurrencyCode()
                            ) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?= $block->escapeHtml($_order->getStatusLabel()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(Reorder::class)->canReorder($_order->getEntityId())): ?>
                                <a href="#" 
                                   data-post='<?= $block->escapeHtmlAttr($this->helper(PostHelper::class)->getPostData($block->getReorderUrl($_order))) // phpcs:ignore ?>' 
                                   class="action order btn btn-primary">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
