<?php
/**
 * @author Dominic <dominic@xigen.co.uk>
 */
/** @var \Xigen\OrderHistory\Block\Sales\View $block */
?>
<ul class="items order-links">
    <li class="nav item current">
        <strong><?= $block->escapeHtml(__('Items Ordered')) ?></strong>
    </li>
</ul>
<div class="order-details-items ordered">
    <?php $_order = $block->getOrder() ?>
    <div class="table-wrapper order-items">
        <table class="data table table-order-items"
               id="my-orders-table" 
               summary="<?= $block->escapeHtml(__('Items Ordered')) ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
            <thead>
                <?php if ($block->isPagerDisplayed()): ?>
                    <tr>
                        <td colspan="5" 
                            data-block="order-items-pager-top" 
                            class="order-pager-wrapper order-pager-wrapper-top">
                            <?= $block->getPagerHtml() ?>
                        </td>
                    </tr>
                <?php endif ?>
                <tr>
                    <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                    <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                    <th class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                    <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
                </tr>
            </thead>
            <?php $items = $block->getItems(); ?>
            <?php foreach ($items as $_item):
                if ($_item->getParentItem()):
                    continue;
                endif;
                ?>
                <tbody>
                    <tr id="order-item-row-<?= (int) $_item->getId() ?>">
                        <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
                            <strong class="product name product-item-name">
                                <?= $block->escapeHtml($_item->getName()) ?>
                            </strong>
                            <?= $block->escapeHtml($_item->getDescription()) ?>
                        </td>
                        <td class="col sku" data-th="<?= $block->escapeHtml(__('SKU')) ?>">
                            <?= /* @noEscape */ $block->prepareSku($_item->getSku()) ?>
                        </td>
                        <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                            <?= /* @noEscape */ $block->formatPrice(
                                $_item->getPrice()
                            ) ?>
                        </td>
                        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                            <ul class="items-qty">
                            <?php if ($_item->getQtyOrdered() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $block->escapeHtml(__('Ordered')) ?></span>
                                    <span class="content"><?= (float) $_item->getQtyOrdered() ?></span>
                                </li>
                            <?php endif; ?>
                            <?php if ($_item->getQtyShipped() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $block->escapeHtml(__('Shipped')) ?></span>
                                    <span class="content"><?= (float) $_item->getQtyShipped() ?></span>
                                </li>
                            <?php endif; ?>
                            <?php if ($_item->getQtyCanceled() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $block->escapeHtml(__('Canceled')) ?></span>
                                    <span class="content"><?= (float) $_item->getQtyCanceled() ?></span>
                                </li>
                            <?php endif; ?>
                            <?php if ($_item->getQtyRefunded() > 0): ?>
                                <li class="item">
                                    <span class="title"><?= $block->escapeHtml(__('Refunded')) ?></span>
                                    <span class="content"><?= (float) $_item->getQtyRefunded() ?></span>
                                </li>
                            <?php endif; ?>
                            </ul>
                        </td>
                        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                        <?= /* @noEscape */ $block->formatPrice(
                            $_item->getRowTotal()
                        ) ?>
                        </td>
                    </tr>
                </tbody>
            <?php endforeach; ?>
            <tfoot>
                <?php if ($block->isPagerDisplayed()): ?>
                    <tr>
                        <td colspan="5" 
                            data-block="order-items-pager-bottom" 
                            class="order-pager-wrapper order-pager-wrapper-bottom">
                            <?= $block->getPagerHtml() ?>
                        </td>
                    </tr>
                <?php endif ?>
                <tr class="subtotal">
                    <th colspan="4" class="mark" scope="row">
                        <?= $block->escapeHtml(__('Subtotal')) ?>
                    </th>
                    <td class="amount" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                        <span class="price"><?= /* @noEscape */ $block->formatPrice(
                            $_order->getSubtotal()
                        ) ?></span>
                    </td>
                </tr>
                <tr class="shipping">
                    <th colspan="4" class="mark" scope="row">
                        <?= $block->escapeHtml(__('Shipping &amp; Handling')) ?>
                    </th>
                    <td class="amount" data-th="<?= $block->escapeHtml(__('Shipping &amp; Handling')) ?>">
                        <span class="price"><?= /* @noEscape */ $block->formatPrice(
                            $_order->getShippingAmount()
                        ) ?></span>
                    </td>
                </tr>
                <tr class="grand_total">
                    <th colspan="4" class="mark" scope="row">
                        <strong><?= $block->escapeHtml(__('Grand Total')) ?></strong>
                    </th>
                    <td class="amount" data-th="<?= $block->escapeHtml(__('Grand Total')) ?>">
                        <strong><span class="price"><?= /* @noEscape */ $block->formatPrice(
                            $_order->getGrandTotal()
                        ) ?></span></strong>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Order Information')) ?></strong>
        </div>
        <div class="block-content">
            <?php if (!$_order->getIsVirtual()): ?>
                <div class="box box-order-shipping-address">
                    <strong class="box-title"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></strong>
                    <div class="box-content">
                        <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getShippingAddress()) // phpcs:ignore ?></address>
                    </div>
                </div>

                <div class="box box-order-shipping-method">
                    <strong class="box-title">
                        <span><?= $block->escapeHtml(__('Shipping Method')) ?></span>
                    </strong>
                    <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?= $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml(__('No shipping information available')) ?>
                    <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="box box-order-billing-address">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </strong>
                <div class="box-content">
                    <address><?= /* @noEscape */ $block->getFormattedAddress($_order->getBillingAddress()) // phpcs:ignore ?></address>
                </div>
            </div>
            <div class="box box-order-billing-method">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Payment Method')) ?></span>
                </strong>
                <div class="box-content">
                    <?= $block->escapeHtml(__('Imported from previous system')) ?>
                </div>
            </div>
        </div>
    </div>


    <div class="actions-toolbar">
        <div class="primary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml($block->getBackTitle()) ?></span>
            </a>
        </div>
    </div>
</div>