name: PHPStan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MilesChou/composer-action@master
      with:
        args: install
    - name: PHPStan
      run: docker run --rm -v $PWD:/code domw/phpstan analyze ./src